# Web Modeler chart
# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml


global:
  identity:
    auth:
      enabled: true
  license:
    existingSecret: "camunda-license"
    existingSecretKey: "key"

prometheusServiceMonitor:
  enabled: false


identity:
  enabled: true
  postgresql:
    enabled: false
    #  https://download.oracle.com/otn-pub/otn_software/jdbc/237/ojdbc17.jar.
  initContainers:
    - name: download-jdbc-driver
      image: curlimages/curl:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - curl -L -o /extraDrivers/ojdbc17.jar https://raw.githubusercontent.com/pierre-yves-monnet/C8-SpringBoot-Kerberos-Oracle/refs/heads/main/driver/ojdbc17.jar

      volumeMounts:
        - name: jdbcdrivers
          mountPath: /extraDrivers
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
  command:
    - /bin/sh
    - -c
    - java -cp "/extraDrivers/ojdbc17.jar:/app/identity.jar" org.springframework.boot.loader.launch.JarLauncher
  env:
    - name: LOGGING_LEVEL_ROOT
      value: DEBUG
    - name: SPRING_PROFILES_ACTIVE
      value: oidc
    - name: MULTI_TENANCY_ENABLED
      value: "true"
    - name: SPRING_JPA_DATABASE
      value: oracle
    - name: SPRING_DATASOURCE_URL
      value: jdbc:oracle:thin:@//oracle-db:1521/XE
    - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: oracle.jdbc.OracleDriver
    - name: SPRING_JPA_SHOW-SQL
      value: "true"
    - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
      value: "true"
    - name: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
      value: TRACE
    - name: SPRING_DATASOURCE_USERNAME
      value: oraidentity
    - name: SPRING_DATASOURCE_PASSWORD
      value: MySecurePassword123
    - name: SPRING_JPA_HIBERNATE_DDL-AUTO
      value: update
    - name: JAVA_OPTS
      value: "-Dloader.path=/extraDrivers"
  extraVolumeMounts:
    - name: jdbcdrivers
      mountPath: /extraDrivers
  extraVolumes:
    - name: jdbcdrivers
      emptyDir: { }

identityKeycloak:
  enabled: true


keycloak:
  enabled: true

webModeler:
  enabled: false
  restapi:
    mail:
      fromAddress: "pierre-yves.monnet@camunda.com"

operate:
  enabled: false


tasklist:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: false



zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1

  env:



zeebe-gateway:
  replicas: 1


