# Web Modeler chart
# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml


global:
  identity:
    auth:
      enabled: true

  # https://docs.camunda.io/docs/self-managed/setup/install/#configure-license-key
  license:
    key: >
      --------------- BEGIN CAMUNDA LICENSE KEY ---------------
      X6CnHxJCaOyKaL43aM3FD3wMtBzgpbjjTZ0Vpwik/we5tGeqmFjDvmWwR
      L+iGwmFbHxwXlyzWqAMhYJBsOJHyjtV5Ntxcn4Nqw45Bjo1++t1XMZuhK
      YDtdygvM7eoaK2BBXs3EoeBCZnKXV1Ccvyr6jcLNA01TrGVVk1UZSQUhY
      YaejV30A4weCBgojtdy5cawieVmWE/tVsThEKRaP+hyuwPnPbj0qWn/MY
      d4wGLkSrW85OKpg0vH+KpCu5bKkKPR/+qx2jERp1EE90M8JJD3yZ8L7nA
      rG9Oj35/4kLss8wzHFyzdp4NBiZ/+LN9B65RyMD+YuTlyyoMu7aV2ZddQ
      G99pNfB0yBi+QNTlg0W4k5OQ5IuBhCdyRfhfwmxCsI+L1o+q54cOpCmGz
      EbiVio4Zo72OgzvI2X7MUZnyef2PC86MUTZKWhhKglRRq3Z25lEIcONQv
      C5TqWlhxYabK3UUXOj5q/LpRDicIV4hN5hs8eaVVNAAWYNv+t/LSNrCPU
      OIN8K8nOfwpoMzn6ZWSQ3Hbxle5a/LrPMLlVOox1q0e434Iy51ZZcsOem
      XSNLZuXm3qqtb7aqOyJu8RZ4zTd6/Pc8ed8ziBSfr7GNnSVzwo3HXN1dV
      1Udeliux57X0x++D4XLgtAKqxExJyuBy2B/ZtqILyDllRbjadVuuEG30=;
      customer = testaccount_camunda;
      expiryDate = unlimited;
      licenseType = production;
      startDate = 2024-10-11;
      ---------------  END CAMUNDA LICENSE KEY  ---------------

prometheusServiceMonitor:
  enabled: false


identity:
  enabled: true
  keycloak:
    url:
      protocol: "http"
      host: "camunda-keycloak-0"
      port: "80"
  postgresql:
    enabled: false
  initContainers:
    - name: download-jdbc-driver
      image: curlimages/curl:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - curl -L -o /extraDrivers/ojdbc17.jar https://raw.githubusercontent.com/pierre-yves-monnet/C8-SpringBoot-Kerberos-Oracle/refs/heads/main/driver/ojdbc17.jar

      volumeMounts:
        - name: jdbcdrivers
          mountPath: /extraDrivers
      securityContext:
          runAsUser: 1000
          runAsNonRoot: true
  command:
    - /bin/sh
    - -c
    - java -cp "/extraDrivers/ojdbc17.jar:/app/identity.jar" org.springframework.boot.loader.launch.JarLauncher
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: oidc
    - name: SPRING_DATASOURCE_URL
      value: jdbc:oracle:thin:@//oracle-db:1521/XE
    - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: oracle.jdbc.OracleDriver
#    - name: SPRING_JPA_DATABASE-PLATFORM
#      value: org.hibernate.dialect.Oracle12cDialect
    - name: SPRING_JPA_SHOW-SQL
      value: "true"
    - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
      value: "true"
    - name: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
      value: TRACE

    #    - name: SPRING_JPA_DATABASE
#      value: oracle
    - name: SPRING_DATASOURCE_USERNAME
      value: oraidentity
    - name: SPRING_DATASOURCE_PASSWORD
      value: MySecurePassword123
    - name: SPRING_JPA_HIBERNATE_DDL-AUTO
      value: update


    #    - name: KRB5_CONFIG
#      value: /etc/krb5.conf
#    - name: FUNCTIONAL_ACCOUNT
#      value: npa_data_aud
#    - name: DB_KRB5CCNAME
#      value: /kcc/npa_data_aud_krb5cache
#    - name: BSID_USE_APP_IDENTITY_LABEL
#      value: "true"
#    - name: JAVA_OPTS
#      value: "-Dloader.path=/extraDrivers"
#      value: "-Djava.security.krb5.conf=/kcc/krb5.conf -Doracle.net.kerberos5_cc_name=/kcc/npa_data_aud_krb5cache"
  extraVolumeMounts:
    - name: jdbcdrivers
      mountPath: /extraDrivers
    - name: krb5-config
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  extraVolumes:
    - name: jdbcdrivers
      emptyDir: { }
  # krb5-config is a configmap created during the Kerberos application
    - name: krb5-config
      configMap:
        name: krb5-config

identityKeycloak:
  enabled: true

keycloak:
  enabled: true

webModeler:
  enabled: false
  restapi:
    mail:
      fromAddress: "pierre-yves.monnet@camunda.com"

operate:
  enabled: false


tasklist:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: false



zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1

  env:



zeebe-gateway:
  replicas: 1


