apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlnet-ora
data:
  sqlnet.ora: |
    NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT, HOSTNAME)
    DISABLE_OOB=ON
    SQLNET.EXPIRE_TIME=3
    SQLNET.AUTHENTICATION_SERVICES= (BEQ, TCPS, KERBEROS5, NONE)
    SQLNET.FALLBACK_AUTHENTICATION=TRUE
    SQLNET.KERBEROS5_CONF_MIT = TRUE
    SQLNET.AUTHENTICATION_KERBEROS5_SERVICE=FREEPDB1
    SQLNET.KERBEROS5_KEYTAB=/tmp/keytabs/keytab
    SQLNET.KERBEROS5_CONF=/opt/oracle/product/23ai/dbhomeFree/network/admin/krb5.conf
---
# jaas.conf is provided by the oracle setup, and will be used by Identity to connect
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaas-conf
data:
  jaas.conf: |
    Server {
      com.sun.security.auth.module.Krb5LoginModule required
      principal="krbtgt/EXAMPLE.COM@EXAMPLE.COM"
      useKeyTab=true
      keyTab="/tmp/keytabs/camunda-identity-1.keytab"
      doNotPrompt=true
      storeKey=true
      useTicketCache=false
      isInitiator=true;
    };


---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
spec:
  type: ClusterIP
  ports:
    - name: sql
      port: 1521
      targetPort: 1521
    - name: em
      port: 5500
      targetPort: 5500
  selector:
    app: oracle-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      securityContext:
        fsGroup: 54321
      containers:
        - name: oracle-db
          image: container-registry.oracle.com/database/free:latest
          ports:
            - containerPort: 1521
            - containerPort: 5500
          env:
            - name: ORACLE_PASSWORD
              value: MySecurePassword123
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: ora-data
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /tmp/keytabs
              name: kdc-keytab
            - name: krb5-conf
              mountPath: /opt/oracle/product/23ai/dbhomeFree/network/admin/krb5.conf
            - name: sqlnet-ora
              mountPath: /opt/oracle/product/23ai/dbhomeFree/network/admin/sqlnet.ora

      volumes:
        - name: ora-data
          persistentVolumeClaim:
            claimName: oracle-data-pvc
        - name: kdc-keytab
          persistentVolumeClaim:
            claimName: krb5-keytab-pvc
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: sqlnet-ora
          configMap:
            name: sqlnet-ora
        - name: tmp-volume
          emptyDir: {}
      resources:
        requests:
          ephemeral-storage: "100M"
        limits:
          ephemeral-storage: "200M"
