apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krb5-keytab-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krb5-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-conf
data:
  krb5.conf: |
    [libdefaults]
      forwardable = true
      default_realm = EXAMPLE.COM
      supported_enctypes = aes256-cts-hmac-sha1-96:normal aes128-cts-hmac-sha1-96:normal
    
    [realms]
      EXAMPLE.COM = {
        kdc = kdc-kadmin
        supported_enctypes = aes256-cts-hmac-sha1-96:normal aes128-cts-hmac-sha1-96:normal    
       }
    
    [domain_realm]
      .example.com = EXAMPLE.COM
      example.com = EXAMPLE.COM

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb5-kdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krb5-kdc
  template:
    metadata:
      labels:
        app: krb5-kdc
    spec:
      containers:
        - name: init
          image: debian:bullseye
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "------- Start initialisation" && \              
              export DEBIAN_FRONTEND=noninteractive && \
              ls -al /krb5-conf && \
              cp /krb5-conf/krb5.conf /etc/krb5.conf && \
              echo "------- after copy krb5.conf" && \
              ls -al /etc/krb5.conf && \
              cat /etc/krb5.conf && \
              echo "------- apt get " && \
              apt-get update  && \
              echo "------- install -y krb5-kdc" && \
              apt-get install -y krb5-kdc krb5-admin-server && \
              echo "------- create /etc/krb5kdc/kdc.conf";
              
              tee /etc/krb5kdc/kdc.conf <<EOF
              [realms]
              $REALM = {
              acl_file = /etc/krb5kdc/kadm5.acl
              max_renewable_life = 7d 0h 0m 0s
              supported_enctypes = $SUPPORTED_ENCRYPTION_TYPES
              default_principal_flags = +preauth
              }
              EOF
              
              echo "------ create /etc/krb5kdc/kadm5.acl";
              tee /etc/krb5kdc/kadm5.acl <<EOF
              $KADMIN_PRINCIPAL_FULL *
              noPermissions@$REALM X
              EOF
              
              echo "------- end of /kadm5.acl"
              ls -al /etc/krb5kdc/kadm5.acl;
              
              echo "------- Create newRealm";
              krb5_newrealm <<EOF
              $MASTER_PASSWORD
              $MASTER_PASSWORD
              EOF
              
              echo "------- Removing [$KADMIN_PRINCIPAL_FULL] for security";
              kadmin.local -q "delete_principal -force $KADMIN_PRINCIPAL_FULL" && \
              echo "Adding [$KADMIN_PRINCIPAL] principal" && \
              kadmin.local -q "addprinc -pw $KADMIN_PASSWORD $KADMIN_PRINCIPAL_FULL" && \
              kadmin.local -q "delete_principal -force noPermissions@$REALM" && \
              kadmin.local -q "addprinc -pw $KADMIN_PASSWORD noPermissions@$REALM" && \
              kadmin.local -q "addprinc -randkey FREEPDB1/0d1aa63b8227@$REALM" && \
              kadmin.local -q "ktadd -k /tmp/keytabs/keytab FREEPDB1/0d1aa63b8227@$REALM" && \
              kadmin.local -q "addprinc -pw camunda krbuser@$REALM" && \
              kadmin.local -q "addprinc -pw camunda krbtgt/EXAMPLE.COM@EXAMPLE.COM" && \
              rm -f /tmp/keytabs/camunda-identity-1.keytab && \
              kadmin.local -q "ktadd -k /tmp/keytabs/camunda-identity-1.keytab krbtgt/EXAMPLE.COM@EXAMPLE.COM" && \
              chmod -R a+rwx /tmp/keytabs/;
              ls -al /tmp/keytabs
              echo "-------- Done"              
              krb5kdc
              kadmind -nofork

          volumeMounts:
            - name: krb5-conf
              mountPath: /krb5-conf
            - name: krb5-data
              mountPath: /var/lib/krb5kdc
            - name: kdc-keytab
              mountPath: /tmp/keytabs
          env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: MASTER_PASSWORD
              value: masterPassword
            - name: KADMIN_PASSWORD
              value: camunda
            - name: KADMIN_PRINCIPAL
              value: kadmin/admin
            - name: KADMIN_PRINCIPAL_FULL
              value: admin/admin@EXAMPLE.COM
            - name: REALM
              value: EXAMPLE.COM
            - name: SUPPORTED_ENCRYPTION_TYPES
              value: aes256-cts-hmac-sha1-96:normal

          ports:
            - containerPort: 88
              name: kerberos
            - containerPort: 464
              name: kpasswd
            - containerPort: 749
              name: kadmin

      volumes:
        - name: krb5-conf
          configMap:
            name: krb5-conf
        - name: krb5-data
          persistentVolumeClaim:
            claimName: krb5-data-pvc
        - name: kdc-keytab
          persistentVolumeClaim:
            claimName: krb5-keytab-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: krb5-kdc
spec:
  selector:
    app: krb5-kdc
  ports:
    - name: kerberos
      port: 88
      targetPort: 88
    - name: kpasswd
      port: 464
      targetPort: 464
    - name: kadmin
      port: 749
      targetPort: 749
