apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-conf
data:
  krb5.conf: |
    [libdefaults]
    forwardable = true
    default_realm = EXAMPLE.COM
    
    [realms]
    EXAMPLE.COM = {
    kdc = kdc-kadmin
    }
    
    [domain_realm]
    .example.com = EXAMPLE.COM
    example.com = EXAMPLE.COM
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-sqlnet-config
data:
  sqlnet.ora: |
    NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT, HOSTNAME)
    DISABLE_OOB=ON
    SQLNET.EXPIRE_TIME=3
    SQLNET.AUTHENTICATION_SERVICES= (BEQ, TCPS, KERBEROS5, NONE)
    SQLNET.FALLBACK_AUTHENTICATION=TRUE
    SQLNET.KERBEROS5_CONF_MIT = TRUE
    SQLNET.AUTHENTICATION_KERBEROS5_SERVICE=FREEPDB1
    SQLNET.KERBEROS5_KEYTAB=/tmp/keytabs/keytab
    SQLNET.KERBEROS5_CONF=/opt/oracle/product/23ai/dbhomeFree/network/admin/krb5.conf
