apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
spec:
  type: ClusterIP
  ports:
    - name: sql
      port: 1521
      targetPort: 1521
    - name: em
      port: 5500
      targetPort: 5500
  selector:
    app: oracle-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      securityContext:
        fsGroup: 54321
      containers:
        - name: oracle-db
          # image: gvenzl/oracle-xe:21-slim
          image: container-registry.oracle.com/database/free:latest
          ports:
            - containerPort: 1521
            - containerPort: 5500
          env:
            - name: ORACLE_PASSWORD
              value: MySecurePassword123
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oracle-pv
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /tmp/keytabs
              name: kdc-keytab
            - name: oracle-sqlnet-config
              mountPath: /opt/oracle/product/23ai/dbhomeFree/network/admin/sqlnet.ora
              subPath: sqlnet.ora
            - name: kerberos-config
              mountPath: /opt/oracle/product/23ai/dbhomeFree/network/admin/krb5.conf
              subPath: krb5.conf
      volumes:
        - name: oracle-pv
          persistentVolumeClaim:
            claimName: oracle-data
        - name: tmp-volume
          emptyDir: {}
      resources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "2Gi"
